
import { MaintenanceReport } from '../types';
import { Plant } from '../types';

interface ProjectExportData {
  name: string;
  image: string;
  inventory: { plant: Plant; count: number }[];
  maintenance: MaintenanceReport | null;
  timestamp: number;
}

const generateCSS = () => `
  :root {
    --primary: #166534;
    --secondary: #4338ca;
    --text: #1c1917;
    --bg: #fafaf9;
    --surface: #ffffff;
    --border: #e7e5e4;
  }
  body {
    font-family: 'Inter', system-ui, -apple-system, sans-serif;
    line-height: 1.5;
    color: var(--text);
    background: var(--bg);
    margin: 0;
    padding: 0;
    -webkit-print-color-adjust: exact;
  }
  .container {
    max-width: 1000px;
    margin: 0 auto;
    background: var(--surface);
    min-height: 100vh;
    box-shadow: 0 0 20px rgba(0,0,0,0.1);
  }
  header {
    background: var(--primary);
    color: white;
    padding: 3rem 4rem;
    display: flex;
    justify-content: space-between;
    align-items: flex-end;
  }
  h1 { margin: 0; font-size: 2.5rem; letter-spacing: -0.05em; }
  .meta { text-align: right; opacity: 0.9; font-size: 0.9rem; }
  
  .hero-image {
    width: 100%;
    max-height: 600px;
    object-fit: contain;
    background: #000;
    border-bottom: 4px solid var(--secondary);
  }
  
  .content { padding: 4rem; }
  
  section { margin-bottom: 4rem; break-inside: avoid; }
  h2 {
    font-size: 1.5rem;
    border-bottom: 2px solid var(--border);
    padding-bottom: 0.5rem;
    margin-bottom: 1.5rem;
    color: var(--primary);
    text-transform: uppercase;
    letter-spacing: 0.1em;
  }
  
  .inventory-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
    gap: 1.5rem;
  }
  .item-card {
    border: 1px solid var(--border);
    border-radius: 8px;
    padding: 1rem;
    display: flex;
    gap: 1rem;
    align-items: center;
    background: var(--bg);
  }
  .item-thumb {
    width: 60px;
    height: 60px;
    border-radius: 6px;
    object-fit: cover;
    background: #ddd;
  }
  .item-details h3 { margin: 0 0 0.25rem 0; font-size: 1rem; }
  .item-details p { margin: 0; font-size: 0.85rem; color: #666; }
  .badge {
    display: inline-block;
    background: white;
    border: 1px solid var(--border);
    padding: 2px 6px;
    border-radius: 4px;
    font-size: 0.7rem;
    text-transform: uppercase;
    font-weight: bold;
    margin-top: 4px;
  }
  
  .maintenance-grid {
    display: grid;
    gap: 1rem;
  }
  .task-row {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    padding: 1rem;
    border-bottom: 1px solid var(--border);
  }
  .task-main { flex: 1; padding-right: 2rem; }
  .priority-high { color: #dc2626; font-weight: bold; }
  .priority-medium { color: #d97706; }
  .priority-low { color: #2563eb; }
  
  footer {
    text-align: center;
    padding: 2rem;
    font-size: 0.8rem;
    color: #888;
    border-top: 1px solid var(--border);
  }
  
  @media print {
    body { background: white; }
    .container { box-shadow: none; max-width: 100%; }
    header { -webkit-print-color-adjust: exact; }
  }
`;

export const generateBlueprintHTML = (data: ProjectExportData): string => {
  const dateStr = new Date(data.timestamp).toLocaleDateString(undefined, {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>${data.name} - Garden Blueprint</title>
      <style>${generateCSS()}</style>
    </head>
    <body>
      <div class="container">
        <header>
          <div>
            <h1>${data.name}</h1>
            <div style="margin-top:0.5rem">Garden Master Plan</div>
          </div>
          <div class="meta">
            Generated by DreamGarden AI<br>
            ${dateStr}
          </div>
        </header>

        <img src="${data.image}" class="hero-image" alt="Garden Design Render" />

        <div class="content">
          <section>
            <h2>Bill of Materials</h2>
            <div class="inventory-grid">
              ${data.inventory.map(item => `
                <div class="item-card">
                  <img src="${item.plant.imageUrl}" class="item-thumb" alt="${item.plant.name}" crossorigin="anonymous"/>
                  <div class="item-details">
                    <h3>${item.plant.name}</h3>
                    <p>${item.plant.scientificName}</p>
                    <div style="display:flex; gap:0.5rem">
                      <span class="badge">Qty: ${item.count}</span>
                      <span class="badge">${item.plant.sunlight}</span>
                      <span class="badge">${item.plant.water === 'Drought-tolerant' ? 'Low Water' : item.plant.water}</span>
                    </div>
                  </div>
                </div>
              `).join('')}
            </div>
          </section>

          ${data.maintenance ? `
          <section>
            <h2>Maintenance Schedule</h2>
            <div style="background: #eff6ff; padding: 1.5rem; border-radius: 8px; margin-bottom: 2rem;">
              <h3 style="margin-top:0; color: #1e40af;">Seasonal Strategy</h3>
              <p style="margin-bottom:0; color: #1e3a8a;">${data.maintenance.seasonalAdvice}</p>
            </div>
            
            <div class="maintenance-grid">
              ${data.maintenance.tasks.map(task => `
                <div class="task-row">
                  <div class="task-main">
                    <div style="font-weight:bold; margin-bottom:0.25rem;">${task.task}</div>
                    <div style="font-size:0.9rem; color:#555;">${task.description}</div>
                  </div>
                  <div style="text-align:right; min-width: 120px;">
                    <div style="font-size:0.8rem; text-transform:uppercase; color:#888; margin-bottom:0.25rem;">${task.frequency}</div>
                    <div style="font-size:0.8rem;" class="priority-${task.priority.toLowerCase()}">${task.priority} Priority</div>
                  </div>
                </div>
              `).join('')}
            </div>
            
            <div style="margin-top: 2rem; padding-top: 1rem; border-top: 1px dashed var(--border);">
              <strong>Irrigation Protocol:</strong> ${data.maintenance.waterSchedule}
            </div>
          </section>
          ` : ''}
          
          <section>
             <h2>Notes</h2>
             <div style="height: 200px; border: 2px dashed #ddd; border-radius: 8px; display: flex; align-items: center; justify-content: center; color: #aaa;">
               Field Notes Area
             </div>
          </section>
        </div>
        
        <footer>
          Created with DreamGarden AI • Powered by Google Gemini
        </footer>
      </div>
      <script>
        window.onload = () => {
           // Auto-print prompt is optional, uncomment if desired
           // window.print();
        }
      </script>
    </body>
    </html>
  `;
};

export const downloadBlueprint = (data: ProjectExportData) => {
  const html = generateBlueprintHTML(data);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const link = document.createElement('a');
  link.href = url;
  link.download = `${data.name.toLowerCase().replace(/\s+/g, '-')}-blueprint.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
